### ISSUE TITLE
[MSIT] Running with -t is not idempotent

### ISSUE THREAD

**Issue by schmerl** [cmu-able/rainbow#59]
If I run `java -jar target/rainbow-initializer-1.0-SNAPSHOT-shaded.jar -t templates/` and answer `n` to the question, and then run the command again, it does not have the same behavior. It runs and creates the target the second time.

**Comment by lennyzhang** [comment]
This feature was by design. The logic behind it is that after the first run, the user would fill out the config.yml file and then run initializer the second time, so that the system would auto-detect and apply the config.yml file when initializer is run the second time.

However, given the confusion it caused, this feature has been removed.
